### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by paddatrapper** [paddatrapper/CaseTracker#11]
Add logging to file and terminal using sf4j library

**Comment by sphaso** [comment]
The server will return a Staff obj

**Comment by paddatrapper** [comment]
Just to add context: This is relating to logging in. The client sends the server the username and password hash. This is then verified by the server and a boolean result and Staff object are returned to the client. The Staff object is null if the result is false

**Comment by sphaso** [comment]
Isn't the project currently shipping log4j? why are you looking to swap it for sf4j?

**Comment by paddatrapper** [comment]
Currently it ships with nothing. I suggested sf4j because I have some, albeit not much, experience with it

**Comment by paddatrapper** [comment]
This is now half complete. Server is fully logged, while the client still needs to be sorted.

**Comment by paddatrapper** [comment]
Client now fully logged
