### ISSUE TITLE
Isolation Framework

### ISSUE THREAD

**Issue by sphaso** [paddatrapper/CaseTracker#14]
Our TTD practice would benefit a lot from the use of an isolation framework. We just need to pick one.

**Comment by paddatrapper** [comment]
I think [Mockito](https://code.google.com/p/mockito/) would work nicely for our needs. A nice comparison between EasyMock (another IF) and Mockito is available [here](http://www.javaworld.com/article/2073140/to-easymock-or-to-mockito-.html)

**Comment by sphaso** [comment]
+1 for Mockito!

**Comment by paddatrapper** [comment]
Cool. Then Mockito it is. Todo: implement it

**Comment by paddatrapper** [comment]
I've implemented as much as I can. Not sure where else mocking would work

**Comment by sphaso** [comment]
Maybe mock DatabasePersistence in UserRepositoryTest?

**Comment by paddatrapper** [comment]
My only concern there is then the SQL statements are not checked

**Comment by sphaso** [comment]
That's true. You can write an integration test for that. Unit tests shouldn't call external resources.

**Comment by paddatrapper** [comment]
Ok sure. Will do then. I'm leaving for the Netherlands tomorrow, so I'm not sure when I'll be able to do it. If you want to do it feel free, otherwise I'll do it when I can

**Comment by paddatrapper** [comment]
Finished mocking UserRespository
