### ISSUE TITLE
Improve Command Line Parsing

### ISSUE THREAD

**Issue by paddatrapper** [paddatrapper/CaseTracker#19]
Develop/find a formalised way of parsing command line options to the server and client. eg: `-v` to get version, etc.

**Comment by sphaso** [comment]
I think we should establish a grammar first. E.g. Are `-vfx` and `-v -f -x` both ok?  
(what is the use case for having the server called via command line?)

**Comment by paddatrapper** [comment]
Thinking about it now the only time I can see command like invocation being useful is when running the server (as client machines are windows for NSPCA)... Even then the only thing I can think of is `-v` checking version being used. Perhaps this isn't a useful feature actually - more work than it is worth.
