### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by paddatrapper** [paddatrapper/CaseTracker#2]
Implement the following:
- [x] Login
- [x] Case management
  - [x] Add cases
  - [x] Edit cases
- [x] User management
  - [x] Add users
  - [x] Edit users
  - [x] Delete users
- [x] Defendant/complainant management
  - [x] Add defendant
  - [x] Add complainant
- [x] Calender
- [x] Reporting
  - [x] New complaints
  - [x] Pending cases
  - [x] Animals involved
  - [x] Cases broken down by region

**Comment by sphaso** [comment]
Since I'm already touching part of the Users business logic (having login return Staff) I thought I'd implement methods for managing users altogether on the server side. What user information is editable (can I change lastName but not address? etc.)

**Comment by paddatrapper** [comment]
Admins can change everything except ID numbers as they should not change. I'm not sure what that is for other countries, but essentially in SA it is the unique number that identifies a person. Think it's similar to USA social security number
